import type { ScanResult, Finding } from '@/types';
import { getSeverityCount } from './scoring';

export function generateReportHTML(scan: ScanResult): string {
  const critical = getSeverityCount(scan.findings, 'critical');
  const high = getSeverityCount(scan.findings, 'high');
  const medium = getSeverityCount(scan.findings, 'medium');

  const findingsRows = scan.findings
    .map(
      (f) => `
    <tr>
      <td style="color: ${f.severity === 'critical' ? '#ef4444' : f.severity === 'high' ? '#f97316' : '#eab308'}; font-weight: bold; text-transform: uppercase;">${f.severity}</td>
      <td>${f.type}</td>
      <td>${f.file}</td>
      <td>${f.line}</td>
      <td>${f.maskedSecret}</td>
    </tr>`
    )
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>SecretGuard Security Report - ${scan.project}</title>
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; background: #0a0e14; color: #e2e8f0; padding: 40px; }
    h1 { color: #22c55e; border-bottom: 2px solid #22c55e; padding-bottom: 10px; }
    h2 { color: #94a3b8; margin-top: 30px; }
    .header { display: flex; justify-content: space-between; align-items: center; }
    .score { font-size: 48px; font-weight: bold; color: ${scan.securityScore >= 75 ? '#22c55e' : scan.securityScore >= 50 ? '#eab308' : '#ef4444'}; }
    .stats { display: flex; gap: 20px; margin: 20px 0; }
    .stat-box { background: #141821; padding: 20px; border-radius: 8px; border: 1px solid #1e2a3a; flex: 1; text-align: center; }
    .stat-value { font-size: 32px; font-weight: bold; }
    .stat-label { color: #64748b; font-size: 14px; }
    table { width: 100%; border-collapse: collapse; margin: 15px 0; }
    th { text-align: left; padding: 10px; background: #141821; color: #94a3b8; border-bottom: 2px solid #1e2a3a; }
    td { padding: 10px; border-bottom: 1px solid #1e2a3a; }
    .badge { padding: 4px 12px; border-radius: 4px; font-size: 12px; font-weight: bold; }
    .footer { margin-top: 40px; text-align: center; color: #475569; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <h1>SecretGuard Security Report</h1>
      <p>Detect secrets. Protect code. Ship securely.</p>
    </div>
    <div class="score">${scan.securityScore}/100</div>
  </div>

  <h2>Project Details</h2>
  <div class="stats">
    <div class="stat-box"><div class="stat-value">${scan.project}</div><div class="stat-label">Project</div></div>
    <div class="stat-box"><div class="stat-value">${scan.filesScanned}</div><div class="stat-label">Files Scanned</div></div>
    <div class="stat-box"><div class="stat-value">${scan.linesAnalyzed.toLocaleString()}</div><div class="stat-label">Lines Analyzed</div></div>
    <div class="stat-box"><div class="stat-value">${scan.secretsDetected}</div><div class="stat-label">Secrets Detected</div></div>
  </div>

  <h2>Severity Distribution</h2>
  <div class="stats">
    <div class="stat-box"><div class="stat-value" style="color:#ef4444">${critical}</div><div class="stat-label">Critical</div></div>
    <div class="stat-box"><div class="stat-value" style="color:#f97316">${high}</div><div class="stat-label">High</div></div>
    <div class="stat-box"><div class="stat-value" style="color:#eab308">${medium}</div><div class="stat-label">Medium</div></div>
  </div>

  <h2>Findings</h2>
  <table>
    <thead>
      <tr><th>Severity</th><th>Secret Type</th><th>File</th><th>Line</th><th>Masked Secret</th></tr>
    </thead>
    <tbody>${findingsRows}</tbody>
  </table>

  <div class="footer">
    Generated by SecretGuard on ${new Date().toLocaleString()}<br />
    This report is for demonstration purposes only.
  </div>
</body>
</html>`;
}

export function downloadReport(scan: ScanResult): void {
  const html = generateReportHTML(scan);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `secretguard-report-${scan.project}-${Date.now()}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function printReport(scan: ScanResult): void {
  const html = generateReportHTML(scan);
  const w = window.open('', '_blank');
  if (w) {
    w.document.write(html);
    w.document.close();
    w.print();
  }
}
